@startuml

actor user
participant "UserAgent" as ua
participant "OIDC Client(RP)" as rp
participant "Keycloak(OP)" as op

== Authorization Request ==

user -> ua : acccess

activate ua

ua -> rp : Authorization parameter create request
note right
  GET /authorization-flow
end note
rp -> rp : generate state, nonce
rp -> rp : generate\ncode_verifier, code_challenge
rp -> rp : store parameters\nin HTTP ession
rp --> ua : Authorization parameters
user -> ua: start \nAuthorization Request
ua -> rp : submit parameters
note right
  POST /authorize
end note
deactivate ua

activate rp
rp -> rp : confirm\nparameters
rp --> ua : redirect
deactivate rp

ua -> op :  Authorization Request
activate ua
note right
  GET /authorize
end note

op -> op : confirm\nparameters
op --> ua : display Login Page
user -> ua : input ID/PW
ua -> op : submit authentication information
note right
  POST /login
end note
op -> op : confirm\nID/PW
op --> ua : redirect
ua -> rp : Authorization Response
deactivate ua

rp -> rp : verify state\nextract Authorization Code

== Token Request ==

user -> ua : start\nToken Request

ua -> rp : start Token Request
activate rp
note right
  POST /token-request
end note
rp -> rp : extract code_challenge\nfrom HTTP session
rp -> op : Token Request

note right
  POST /token
end note

op -> op : confirm\nparameters
op --> rp : Token Response

rp -> rp : verify Access Token(JWT)\nverify id_token
rp -> rp : extract user information
rp --> ua : display user information
deactivate rp

note left
  for the purpose of
  demonstoration
end note

@enduml
