@startuml

actor user
participant "UserAgent" as ua
participant "OIDC Client(RP)" as rp
participant "Keycloak(OP)" as op

== Token Request ==

user -> ua : start\nToken Request

ua -> rp : start Token Request
activate rp
note right
  POST /token-request
end note
rp -> rp : extract code_challenge\nfrom HTTP session
rp -> op : Token Request **with mTLS**

note right
  POST /token
end note

op -> op : verify\nclient certificate
op -> op : confirm\nparameters
op --> rp : Token Response

rp -> rp : verify Access Token(JWT)\nverify id_token
rp -> rp : extract user information
rp --> ua : display user information
deactivate rp

note left
  for the purpose of
  demonstoration
end note

@enduml
