# HTTPS設定
server.port=8081
server.ssl.enabled=true
server.ssl.key-store=classpath:ssl/oidc-https-keystore.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=oidc-client

# mTLS設定（アプリ自身へのクライアント認証）
server.ssl.client-auth=need
server.ssl.trust-store=classpath:ssl/oidc-mtls-client-truststore.p12
server.ssl.trust-store-password=changeit
server.ssl.trust-store-type=PKCS12

# Springアプリケーション設定
spring.application.name=oidc-client
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Keycloak 設定
application.oidc.host=https://localhost:8443
application.oidc.context-path=/realms/myrealm/protocol/openid-connect
application.oidc.client-id=semi_client
application.oidc.issuer=https://localhost:8443/realms/myrealm

# Keycloak への mTLS 通信用設定（クライアント証明書 + Keycloakサーバtruststore）
application.keycloak.mtls.key-store=ssl/oidc-mtls-client-keystore.p12
application.keycloak.mtls.key-store-password=changeit
application.keycloak.mtls.key-store-type=PKCS12

application.keycloak.mtls.trust-store=ssl/keycloak-server-truststore.p12
application.keycloak.mtls.trust-store-password=changeit
application.keycloak.mtls.trust-store-type=PKCS12

# PKCE設定
application.pkce.code-verifier-size=64

# アプリ内パス設定
application.path.root=/
application.path.home=/home
application.path.authorization-flow=/authorization-flow
application.path.authorize=/authorize
application.path.callback=/callback
application.path.token-request=/token-request
application.path.token=/token

# アプリ実行時にパッケージ全体の DEBUG を有効にする
logging.level.com.example.oidcclient=DEBUG